'use client'

import { useEffect, useState } from 'react'
import Image from 'next/image'
import { ArrowUpRight, Check, ChevronLeft, ChevronRight, Download, Mail, Menu, Moon, Phone, Sun, X, MessageCircle } from 'lucide-react'

const profileImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-09-25%20at%202.07.35%20AM-wQ6RQx22mp4rzurQAmUm5GLXN3wUz6.jpeg'
const spotmeLogo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/spotme_logo-maJKS4MuzgTsK8kvMsFttAY3ZGHCVP.png'
const awardImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-09-25%20at%201.29.35%20AM-kDxgj17C87KLiTYX2UDvpjJqiyT5wN.jpeg'
const cvLink = 'https://blobs.vusercontent.net/blob/Ayat_Abd_Elazeez_CV-CAzs19LRDNs15Jros19D2ngfGeWIzM.pdf'
const cppCertificateImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-6xwOHiYIMIT5WjZlEOKrhLz3PqLaKC.png'
const flutterCertificateImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-08-23%20at%209.22.05%20PM-cDs0MSWfpIFi4ZERvA69OoL6h690Wx.jpeg'
const hospitalImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-LhDrNhLdJl5UWymFGhz9DYZOFLlJUj.png'
const miniOsImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-qrz3LSZKBv1jzBWkGp7wk3ElbzkUjF.png'

const navItems = ['Home', 'About', 'Education', 'Certificates', 'Skills', 'Experience', 'Services', 'Projects', 'Achievements', 'Testimonials']
const skills = {
  'Data Engineering': ['Python', 'SQL', 'Data Cleaning', 'ETL Fundamentals', 'Databases'],
  'Software Development': ['C++', 'OOP', 'Data Structures', 'Git/GitHub'],
  'Flutter Development': ['Flutter', 'Dart', 'UI Flows'],
  'Soft Skills': ['Problem Solving', 'Presentation Skills', 'Planning'],
}

function SectionTitle({ eyebrow, children }: { eyebrow: string; children: React.ReactNode }) {
  return <div className="section-title"><span className="eyebrow">{eyebrow}</span><h2>{children}</h2></div>
}
function Tags({ items }: { items: string[] }) { return <div className="tags">{items.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div> }
function Detail({ label, children }: { label: string; children: React.ReactNode }) { return <div className="detail"><span>{label}</span><p>{children}</p></div> }
function GithubIcon({ size = 20 }: { size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 .7a12 12 0 0 0-3.79 23.39c.6.11.82-.26.82-.58v-2.25c-3.34.73-4.04-1.61-4.04-1.61-.55-1.39-1.34-1.76-1.34-1.76-1.09-.75.08-.74.08-.74 1.2.09 1.84 1.24 1.84 1.24 1.07 1.83 2.8 1.3 3.49.99.11-.78.42-1.3.76-1.6-2.67-.3-5.47-1.34-5.47-5.94 0-1.31.47-2.38 1.24-3.22-.12-.3-.54-1.52.12-3.18 0 0 1.01-.32 3.3 1.23a11.5 11.5 0 0 1 6 0c2.29-1.55 3.3-1.23 3.3-1.23.66 1.66.24 2.88.12 3.18.77.84 1.24 1.91 1.24 3.22 0 4.61-2.8 5.63-5.48 5.93.43.37.81 1.1.81 2.22v3.29c0 .32.22.69.83.57A12 12 0 0 0 12 .7Z" /></svg> }
function LinkedinIcon({ size = 20 }: { size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6.5 8.25H3V21h3.5V8.25ZM4.75 3A2.05 2.05 0 1 0 4.75 7.1 2.05 2.05 0 0 0 4.75 3ZM21 13.67c0-3.84-2.05-5.63-4.78-5.63a4.13 4.13 0 0 0-3.72 2.05V8.25H9V21h3.5v-6.3c0-1.66.31-3.27 2.37-3.27 2.03 0 2.05 1.91 2.05 3.38V21H21v-7.33Z" /></svg> }

export default function Page() {
  const [dark, setDark] = useState(true)
  const [language, setLanguage] = useState<'EN' | 'AR'>('EN')
  const [menuOpen, setMenuOpen] = useState(false)
  const [active, setActive] = useState('Home')
  const [testimonial, setTestimonial] = useState(0)
  const [sent, setSent] = useState(false)

  useEffect(() => {
    document.documentElement.classList.toggle('light', !dark)
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-30% 0px -60% 0px' })
    navItems.forEach((item) => observer.observe(document.getElementById(item.toLowerCase())!))
    return () => observer.disconnect()
  }, [dark])

  const go = (id: string) => { document.getElementById(id.toLowerCase())?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }
  const testimonials = [
    ['Ayat shows remarkable dedication and structured thinking when dealing with data workflows. Her ability to plan before writing code makes her work efficient and clean.', 'Habiba Ramadan', 'Classmate, Faculty of Engineering, Al-Azhar University', 'Structured'],
    ["Ayat communicates clearly and solves problems effectively. She keeps things organized and makes sure the team stays on track — she's the person who ties the details together.", 'Alya Tarq', 'Teammate, SpotMe project', 'Organized'],
    ['… always committed to her work while bringing creative ideas and thoughtful touches to every task.', 'Jana Mohamed', 'Colleague, Digital Egypt Pioneers Initiative (DEPI)', 'Committed'],
  ]

  return <div className="site-shell">
    <header className="navbar"><a className="logo" href="#home" onClick={() => go('Home')}>A.A</a><nav className={menuOpen ? 'nav-links open' : 'nav-links'}>{navItems.map((item) => <a className={active === item ? 'active' : ''} key={item} href={`#${item.toLowerCase()}`} onClick={() => go(item)}>{item}</a>)}</nav><div className="nav-actions"><button className="icon-button" aria-label="Toggle theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="icon-button language-button" aria-label={`Switch to ${language === 'EN' ? 'Arabic' : 'English'}`} onClick={() => { const next = language === 'EN' ? 'AR' : 'EN'; setLanguage(next); document.documentElement.dir = next === 'AR' ? 'rtl' : 'ltr' }}><span>{language === 'EN' ? 'ع' : 'EN'}</span></button><button className="button small connect-desktop" onClick={() => go('Contact')}>Connect Me</button><button className="menu-button" aria-label="Toggle menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div></header>

    <main>
      <section id="home" className="hero section"><div className="hero-copy"><span className="eyebrow">Hello, I&apos;m</span><h1>Ayat Abd Elazeez</h1><p className="role">&lt; Data Engineer /&gt;</p><p className="hero-text">I help startups and small business owners turn messy raw data into clean, reliable datasets through precise, well-documented Python workflows, delivered on time.</p><div className="button-row"><button className="button" onClick={() => go('Projects')}>View My Work <ArrowUpRight size={16} /></button><a className="button secondary" href={cvLink} target="_blank" rel="noreferrer"><ArrowUpRight size={16} /> View CV</a></div><div className="socials hero-socials"><a href="https://github.com/Ayatabdelazeez" target="_blank" rel="noreferrer" aria-label="GitHub"><GithubIcon size={22} /></a><a href="https://www.linkedin.com/in/ayat-abd-elazeez-57bb663b4" target="_blank" rel="noreferrer" aria-label="LinkedIn"><LinkedinIcon size={22} /></a></div></div><div className="hero-visual"><div className="portrait-frame"><Image src={profileImage} alt="Ayat Abd Elazeez" fill priority sizes="(max-width: 768px) 80vw, 420px" /></div><span className="float-badge badge-one">Python</span><span className="float-badge badge-two">SQL</span><span className="float-badge badge-three">ETL</span></div></section>

      <section id="about" className="section"><SectionTitle eyebrow="01 / About">Turning messy data into reliable results, one documented step at a time.</SectionTitle><div className="about-content"><div><p>Hello, I&apos;m Ayat Abd Elazeez, a Data Engineer who helps startups and small business owners collect, clean, and structure their data. I&apos;m an engineering student in Systems &amp; Computers at Al-Azhar University, currently training in data engineering with the Digital Egypt Pioneers Initiative (DEPI).</p><p>I specialize in Python, SQL, and ETL workflows that turn messy spreadsheets and raw exports into clean, ready-to-use datasets. What sets my work apart is precision: I document every step so results are reproducible, I deliver on time, and I only commit to what I can deliver, so you always know what to expect.</p><Tags items={['Python', 'SQL', 'ETL', 'Data Cleaning', 'Git/GitHub']} /></div></div></section>

      <section id="education" className="section"><SectionTitle eyebrow="02 / Education">Education</SectionTitle><div className="education-grid education-stack"><div><p className="card-label">EDUCATION</p><article className="card education-card"><span className="timeline-dot" /><h3>Bachelor of Engineering — Systems &amp; Computers</h3><p>Faculty of Engineering, Al-Azhar University</p><span className="muted">Expected graduation: 2028</span></article></div><div id="certificates" className="certificates-column"><p className="card-label">CERTIFICATES</p><div className="certificate-grid"><article className="card certificate-card"><div className="certificate-image"><Image src={cppCertificateImage} alt="C++ Programming Language certificate" fill sizes="(max-width: 768px) 100vw, 300px" /></div><p className="accent">IT Sharks</p><h3>C++ Programming Language</h3><span className="muted">Nov 2025 – Apr 2026</span><p>Completed the C++ programming language program.</p></article><article className="card certificate-card"><div className="certificate-image"><Image src={flutterCertificateImage} alt="Flutter Delegate certificate" fill sizes="(max-width: 768px) 100vw, 300px" /></div><p className="accent">SBS (Step By Step)</p><h3>Flutter Delegate — Certificate of Achievement</h3><span className="muted">21 Aug 2026</span><p>Attended the SBS sessions and completed the project as a Flutter Delegate.</p></article></div></div></div></section>

      <section id="skills" className="section"><SectionTitle eyebrow="03 / Skills">Skills that keep projects moving.</SectionTitle><div className="skills-grid">{Object.entries(skills).map(([name, tags]) => <article className="card skill-card" key={name}><span className="skill-index">0{Object.keys(skills).indexOf(name) + 1}</span><h3>{name}</h3><p>{name === 'Data Engineering' ? 'Collecting, cleaning, structuring and documenting datasets for reliable analysis.' : name === 'Software Development' ? 'Building structured programs with a focus on maintainable code and problem-solving.' : name === 'Flutter Development' ? 'Creating clean mobile screens and practical user flows for team projects.' : 'Planning before coding, clear communication and careful, detail-focused work.'}</p><Tags items={tags} /></article>)}</div></section>

      <section id="experience" className="section"><SectionTitle eyebrow="04 / Experience">Experience</SectionTitle><div className="timeline"><article className="timeline-item"><span className="timeline-dot" /><div className="experience-head"><div><h3>Data Engineering Trainee</h3><p>Digital Egypt Pioneers Initiative (DEPI)</p></div><div className="experience-meta"><span>Jul 2026 – Present</span><span>Training</span></div></div><div className="strips"><div><b>CHALLENGE</b><p>Learning to turn raw, messy datasets into reliable, reviewable results in a professional training program.</p></div><div><b>ACTION</b><p>• Practiced collecting, cleaning, and structuring datasets<br />• Documented every step so results are reproducible</p></div></div><Tags items={['Python', 'SQL', 'Data Cleaning']} /></article><article className="timeline-item"><span className="timeline-dot" /><div className="experience-head"><div><h3>Flutter Developer &amp; Member</h3><p>SpotMe Conference + SBS (Step By Step) Student Activity</p></div><div className="experience-meta"><span>Team project</span><span>Student activity</span></div></div><div className="strips"><div><b>CHALLENGE</b><p>Building a smooth first-use experience for a platform connecting young athletes with scouts and academies, working with a large team from several committees.</p></div><div><b>ACTION</b><p>• Built the splash and onboarding screens<br />• Contributed to the scout and player screens<br />• Attended technical sessions and worked on collaborative team projects</p></div><div><b>RESULT</b><p>Team won Best Team and a 15,000 EGP cash prize.</p></div></div><Tags items={['Flutter', 'Dart', 'Teamwork']} /></article></div></section>

      <section id="services" className="section"><SectionTitle eyebrow="05 / Services">Practical help for data-heavy teams.</SectionTitle><div className="services-grid">{[['01', 'Data Cleaning & Organization', 'Turn messy spreadsheets and raw exports into tidy, consistent, ready-to-use datasets.', 'Messy data wastes time and leads to wrong decisions.', 'Clean datasets with every step documented, so you can reproduce and trust them.', ['Python', 'Data Cleaning']], ['02', 'Data Structuring & Documentation', 'Organize scattered data into a clear structure with step-by-step documentation.', 'Data spread across files with no clear process.', 'A structured, documented workflow your team can rerun and review.', ['Python', 'SQL', 'ETL Fundamentals']], ['03', 'Flutter App Screens', 'Build clean, responsive Flutter screens and user flows from a design or a simple brief.', 'Early-stage products need a polished first-use experience fast.', 'Ready-to-use screens with smooth onboarding flows.', ['Flutter', 'Dart']]].map(([num, name, what, problem, result, tags]) => <article className="card service-card" key={name as string}><span className="service-num">{num}</span><h3>{name}</h3><Detail label="What" >{what}</Detail><Detail label="Problem">{problem}</Detail><Detail label="Result">{result}</Detail><Tags items={tags as string[]} /></article>)}</div></section>

      <section id="projects" className="section"><SectionTitle eyebrow="06 / Projects">Selected work, built with care.</SectionTitle><div className="projects-list"><article className="project-card featured"><div className="project-cover"><Image src={spotmeLogo} alt="SpotMe logo" fill sizes="(max-width: 768px) 100vw, 900px" /></div><div className="project-body"><span className="badge">Team Project</span><h3>SpotMe</h3><p className="project-one-liner">A Flutter/Dart platform connecting young athletes with scouts and academies.</p><Detail label="Problem">Young athletes struggle to get discovered by scouts and academies.</Detail><Detail label="Role">Flutter Developer. Built the splash and onboarding screens and contributed to the scout and player screens.</Detail><Detail label="Solution">Designed smooth first-use flows and helped implement the screens where scouts browse players and athletes present their profiles.</Detail><Detail label="Tools">Flutter, Dart</Detail><Detail label="Result">Won Best Team and a 15,000 EGP cash prize at the SpotMe Conference.</Detail><Tags items={['Flutter', 'Dart']} /><a className="text-link" href="https://github.com/Ayatabdelazeez/SPOT_ME-main" target="_blank" rel="noreferrer">View Project <ArrowUpRight size={16} /></a></div></article><ProjectCard title="Hospital Management System" badge="Team Project" tagline="A console-based system connecting managers, doctors and patients." cover="[Cover image]" details={[['Problem', 'Hospital data, appointments and patient workflows are hard to manage without a clear structure.'], ['Role', 'Developer on the team, responsible for the patient module.'], ['Solution', 'Built the patient module (patient registration and patient data handling) inside a team-developed C++ system that manages appointments, medical records and billing.'], ['Tools', 'C++, OOP, Linked Lists, ERD'], ['Result', 'Graded Excellent and earned a certificate.']]} button="https://docs.google.com/presentation/d/1rfesSoor5iCZfA2xqVM-qiye37z7wjcR/edit?usp=sharing&ouid=110184478307901612644&rtpof=true&sd=true" /><ProjectCard title="Mini OS Simulator" badge="Personal Project" tagline="A Python virtual file system with persistent storage." cover="[Cover image]" details={[['Problem', 'Understanding how operating systems manage files is hard without building one.'], ['Role', 'Sole developer. Designed and built it from scratch.'], ['Solution', 'Implemented directories and files with commands such as ls, mkdir, cd, read, write, rm and tree, and saved the data to a JSON file after every command so it persists between sessions.'], ['Tools', 'Python, JSON'], ['Result', 'A working command-line prototype with persistent storage.']]} button="[GitHub link]" /></div></section>

      <section id="achievements" className="section"><SectionTitle eyebrow="07 / Achievements">Milestones worth remembering.</SectionTitle><div className="achievement-grid"><article className="card achievement-card"><div className="achievement-image"><Image src={awardImage} alt="SpotMe award check" fill sizes="(max-width: 768px) 100vw, 420px" /></div><p className="accent">SpotMe Conference</p><h3>Best Team + 15,000 EGP Prize</h3><p>My team won Best Team and a cash prize for the SpotMe platform.</p></article><article className="card achievement-card"><div className="achievement-icon"><Check /></div><p className="accent">Hospital Management System</p><h3>Excellent Grade + Certificate</h3><p>Graded Excellent for a team-built hospital management system; I built the patient module.</p></article></div></section>

      <section id="testimonials" className="section"><SectionTitle eyebrow="08 / Testimonials">Kind words from people I&apos;ve worked with.</SectionTitle><div className="testimonial-wrap"><button className="slider-button" aria-label="Previous testimonial" onClick={() => setTestimonial((testimonial + testimonials.length - 1) % testimonials.length)}><ChevronLeft /></button><article className="testimonial-card"><span className="quote-mark">“</span><blockquote>{testimonials[testimonial][0]}</blockquote><div><h3>{testimonials[testimonial][1]}</h3><p>{testimonials[testimonial][2]}</p><span className="tag">{testimonials[testimonial][3]}</span></div></article><button className="slider-button" aria-label="Next testimonial" onClick={() => setTestimonial((testimonial + 1) % testimonials.length)}><ChevronRight /></button></div><div className="slider-dots">{testimonials.map((_, i) => <button key={i} aria-label={`Show testimonial ${i + 1}`} className={i === testimonial ? 'current' : ''} onClick={() => setTestimonial(i)} />)}</div></section>

      <section id="contact" className="section contact-section"><SectionTitle eyebrow="09 / Contact">Let&apos;s Talk</SectionTitle><p className="contact-subline">Let&apos;s build something reliable.</p><div className="contact-grid"><div className="contact-info"><a className="contact-card" href="mailto:ayatabdelazeezmohamed@gmail.com"><Mail /><span><b>Email</b>ayatabdelazeezmohamed@gmail.com</span><ArrowUpRight /></a><a className="contact-card" href="tel:+201024656139"><Phone /><span><b>Phone</b>+20 102 465 6139</span><ArrowUpRight /></a><a className="contact-card" href="https://wa.me/201024656139" target="_blank" rel="noreferrer"><MessageCircle /><span><b>WhatsApp</b>Message me directly</span><ArrowUpRight /></a><div className="socials"><a href="https://www.linkedin.com/in/ayat-abd-elazeez-57bb663b4" target="_blank" rel="noreferrer" aria-label="LinkedIn"><LinkedinIcon size={20} /></a><a href="https://github.com/Ayatabdelazeez" target="_blank" rel="noreferrer" aria-label="GitHub"><GithubIcon size={20} /></a></div></div><form className="contact-form card" onSubmit={(e) => { e.preventDefault(); setSent(true) }}><label>Your Name<input required name="name" /></label><label>Your Email<input required type="email" name="email" /></label><label>Subject<input required name="subject" /></label><label>Message<textarea required name="message" rows={5} /></label><button className="button" type="submit">Send Message <ArrowUpRight size={16} /></button>{sent && <p className="success">Message ready to send.</p>}</form></div></section>
    </main>

    <footer><div><h3>Let&apos;s Connect</h3><div className="socials"><a href="https://www.linkedin.com/in/ayat-abd-elazeez-57bb663b4" target="_blank" rel="noreferrer" aria-label="LinkedIn"><LinkedinIcon size={20} /></a><a href="https://github.com/Ayatabdelazeez" target="_blank" rel="noreferrer" aria-label="GitHub"><GithubIcon size={20} /></a></div></div><div><span className="logo">A.A</span><p>Data Engineer · Giza, Egypt</p></div><div><h3>Who Am I?</h3><p>I&apos;m Ayat, a Data Engineer who turns messy data into clean, reliable datasets.</p></div><div className="footer-bottom">© 2026 Ayat Abd Elazeez. All rights reserved.</div></footer>
  </div>
}

function ProjectCard({ title, badge, tagline, cover, details, button }: { title: string; badge: string; tagline: string; cover: string; details: string[][]; button: string }) {
  const effectiveButton = title === 'Mini OS Simulator' ? 'https://drive.google.com/file/d/1SmkGpF94zIMzXWajxaJeZBcGgYjMa79d/view?usp=sharing' : button
  const realLink = effectiveButton.startsWith('http')
  return <article className="project-card"><div className="project-cover">{title === 'Hospital Management System' ? <Image src={hospitalImage} alt="Hospital Management System logo" fill sizes="(max-width: 768px) 100vw, 900px" /> : title === 'Mini OS Simulator' ? <Image src={miniOsImage} alt="Mini OS Simulator logo" fill sizes="(max-width: 768px) 100vw, 900px" /> : <span>{cover}</span>}</div><div className="project-body"><span className="badge">{badge}</span><h3>{title}</h3><p className="project-one-liner">{tagline}</p>{details.map(([label, value]) => <Detail key={label} label={label}>{value}</Detail>)}<Tags items={title === 'Hospital Management System' ? ['C++', 'OOP', 'Linked Lists', 'ERD'] : ['Python', 'JSON']} />{realLink ? <a className="text-link" href={effectiveButton} target="_blank" rel="noreferrer">View Project <ArrowUpRight size={16} /></a> : <span className="editable-link">{button}</span>}</div></article>
}
